import events from './events'
import eventImage from './eventImage'
import news from './news'
import newsImage from './newsImage'
import faculty from './faculty'
import nonteach from './nonteach'
import principal from './principal'
import vision from './vision'
import timetable from './timetable'
import datesheet from './datesheet'
import results from './results'
import feestructure from './feestructure'
import admissionc from './admissionc'
import admissionp from './admissionp'
import studentlife from './studentlife'
import gallery from './gallery'
import institutefacilities from './institutefacilities'
import contactus from './contactus'
import VP from './VP'
import pride from './pride'
import degrees from './degrees'
import degreeprogram from './degreeprogram'


export const schemaTypes = [events , eventImage, faculty , principal, vision, timetable,datesheet,results, feestructure, admissionc, admissionp, studentlife, gallery, institutefacilities, contactus, nonteach, VP, news, newsImage, pride, degrees, degreeprogram]
